### ISSUE TITLE
Score detail cannot be fetched

### ISSUE THREAD

**Issue by PhotonQuantum** [PhotonQuantum/pysjtu#3]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lightquantum/.local/lib/python3.8/site-packages/pysjtu/models/score.py", line 95, in detail
    self._detail = self._func_detail(self.year, self.term, self.class_id)
  File "/home/lightquantum/.local/lib/python3.8/site-packages/pysjtu/client/api/score.py", line 21, in _get_score_detail
    factors = schemas.ScoreFactorSchema(many=True).load(raw.json()["items"][:-1])  # type: ignore
  File "/home/lightquantum/.local/lib/python3.8/site-packages/httpx/models.py", line 856, in json
    return jsonlib.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 7 column 1 (char 13)
```

**Comment by PhotonQuantum** [comment]
iSJTU system updated. Can't reproduce now.
