### ISSUE TITLE
"500error" occurred when logging in

### ISSUE THREAD

**Issue by chshzhe01** [PhotonQuantum/pysjtu#6]
>`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "\Python\Python38\lib\site-packages\pysjtu\client\__init__.py", line 69, in create_client
    sess = Session(username=username, password=password, _mocker_app=_mocker_app)
  File "\Python\Python38\lib\site-packages\pysjtu\session.py", line 134, in __init__
    self.loads({"username": username, "password": password})
  File "\Python\Python38\lib\site-packages\pysjtu\session.py", line 662, in loads
    self.login(self._username, self._password)
  File "\Python\Python38\lib\site-packages\pysjtu\session.py", line 592, in login
    login_page_req = self._secure_req(partial(self.get, consts.LOGIN_URL, validate_session=False))
  File "\Python\Python38\lib\site-packages\pysjtu\session.py", line 94, in _secure_req
    return ref()
  File "\Python\Python38\lib\site-packages\pysjtu\session.py", line 263, in get
    return self.request(
  File "\Python\Python38\lib\site-packages\pysjtu\session.py", line 202, in request
    raise e
  File "\Python\Python38\lib\site-packages\pysjtu\session.py", line 198, in request
    rtn.raise_for_status()
  File "s\Python\Python38\lib\site-packages\httpx\models.py", line 846, in raise_for_status
    raise HTTPError(message, response=self)
httpx.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://jaccount.sjtu.edu.cn/jaccount/jalogin?sid=jaoauth2*******8&client=CJxHHmK8yp%2Bm*******3shBxiYMm7KTwBwZj43LOx%2Fpz&returl=*******nlvLGOVe%2FnSz6fJBBkt7*******Tt6w6b%2FuRlHXlydUr*******jg7lDT3j4yhbudB2emeheD%2F85L76ok4oqGYynv*******tFAtOAj147rFuv*******TZ3YTg%3D%3D&se=*******ajbTGmIjZA3mXQ0A3zJm7yiT65j2jXIjxGVKq0h*******TWdKFR0t0XMmw%3D%3D
For more information check: https://httpstatuses.com/500`

**Comment by PhotonQuantum** [comment]
Nice catch! I've just pushed a hotfix to fix this problem.

Unfortunately, the CI is now broken so I can't make a new release at once. I'll publish it to PyPI once I get this fixed (in about half an hour).

In the meantime, you may use the master branch directly.

**Comment by chshzhe01** [comment]
Thanks a lot.
